services:
  uptime-kuma-discord-bot:
    image: boker02/uptime-kuma-discord-bot:latest
    container_name: uptime-kuma-discord-bot
    restart: unless-stopped
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      UPTIME_KUMA_URL: ${UPTIME_KUMA_URL:-http://localhost:3001}
      UPTIME_KUMA_USERNAME: ${UPTIME_KUMA_USERNAME}
      UPTIME_KUMA_PASSWORD: ${UPTIME_KUMA_PASSWORD}
      UPDATE_INTERVAL: ${UPDATE_INTERVAL:-60}
      EMBED_COLOR: ${EMBED_COLOR:-5814783}
      ADMIN_USER_IDS: ${ADMIN_USER_IDS:-}

      PUID: 1001
      PGID: 1001
      DATA_DIR: /app/data
    volumes:
      - botdata:/app/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  botdata:
